config/routes.rb
Rails.application.routes.draw do
  resources :breweries
  resources :locations
  resources :events
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'breweries#index' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brewery.rb
class Brewery < ApplicationRecord
	has_many :locations
	has_many :events, through: :locations
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :location, foreign_key: "location_uuid", primary_key: "uuid"
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :brewery
	has_many :events, foreign_key: "location_uuid", primary_key: "uuid"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @breweries = Brewery.all
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show

  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :twitter, :facebook, :instagram, :website, :photo, :description)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	layout false
	def show
		brewery = Brewery.find_by_id(params[:id])
		@events = brewery.events.to_json
	end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	layout false
	
	def show
		brewery = Brewery.find_by_id(params[:id])
		@locations = brewery.locations.to_json
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(brewery) do |f| %>
  <% if brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1 id='main-title'>Breweries</h1>

  <div id='list-of-brews'>
    <% @breweries.each do |brewery| %>
      
      <div class='brew-square' id='<%= brewery.id %>'>
        <header class='brew-name'><%= brewery.name %></header>
        <img src="<%= brewery.photo %> " height="200px" width="200px">
      </div>
    
    <% end %>
  </div>
  

<div id="myModal" class="modal">
  

  <div class="modal-content">
    <span class="close">&times;</span> 
    <div height="50px">
      <header class='show-name'></header>
    </div>
    <!-- FIRST DIV WITH PICTURE -->
    <div class="brew-details">
      <nav class='links'>
        <a id="twitter-link" href="">Twitter</a>
        <a id="facebook-link" href="">Facebook</a>
        <a id="instagram-link" href="">Instagram</a>
        <a id='website-link' href="">Website</a></nav>
      <br>
      <img src="" height="420px" width="420px" class="show-photo">
      <p class='show-description'></p>
    </div>  

    <!-- SECOND DIV WITH LOCATIONS -->
    <div class='show-details'>
      <h2> Locations </h2>
      <!-- <div class="show-locations">
      </div> -->
    </div>

    <!-- THIRD DIV WITH EVENTS -->
    <div class='event-details'>
      <h2> Events </h2>
    </div>

  </div>

</div>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form', brewery: @brewery %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brewery.name %>
</p>

<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>

app/views/events/show.html.erb
<%= @events %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/show.html.erb
<%= @locations %>